language: java

services:
  - docker

jobs:
  include:
    - stage: publish_database
      script:
        - docker build -t $DOCKERHUB_USER/database_base ./database
      after_success:
        - echo $DOCKERHUB_PWD | docker login --username $DOCKERHUB_USER --password-stdin
        - docker tag $DOCKERHUB_USER/database_base $DOCKERHUB_USER/database_base:1.1
        - docker push $DOCKERHUB_USER/database_base
    - stage: publish_backend
      script:
        - docker build -t $DOCKERHUB_USER/backend_base ./simple-api
      after_success:
        - echo $DOCKERHUB_PWD | docker login --username $DOCKERHUB_USER --password-stdin
        - docker tag $DOCKERHUB_USER/backend_base $DOCKERHUB_USER/backend_base:1.1
        - docker push $DOCKERHUB_USER/backend_base
    - stage: publish_server
      script:
        - docker build -t $DOCKERHUB_USER/server_base ./httpd
      after_success:
        - echo $DOCKERHUB_PWD | docker login --username $DOCKERHUB_USER --password-stdin
        - docker tag $DOCKERHUB_USER/server_base $DOCKERHUB_USER/server_base:1.1
        - docker push $DOCKERHUB_USER/server_base
    - stage: deploy
      addons:
        ssh_known_hosts: serinkan-asci.takima.io
      install:
        - sudo apt update
        - sudo apt install software-properties-common
        - sudo apt-add-repository --yes --update ppa:ansible/ansible
        - sudo apt install ansible
      script:
        - openssl aes-256-cbc -K $encrypted_ec0015db4ac4_key -iv $encrypted_ec0015db4ac4_iv -in id_rsa.enc -out /tmp/deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_rsa
        - ssh-add /tmp/deploy_rsa
        - ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml
